<Project>
  <PropertyGroup>

    <_SolutionRoot>$(MSBuildThisFileDirectory)</_SolutionRoot>

    <_RelativePath>$([MSBuild]::MakeRelative($(_SolutionRoot), $(MSBuildProjectDirectory)))</_RelativePath>

    <_PathId>$(_RelativePath.Replace('\','.').Replace('/','.'))</_PathId>

    <_BuildPath>$([System.IO.Path]::GetTempPath())build/</_BuildPath>
    <_Path>$(Configuration)/$(_PathId)/</_Path>

    <OutputPath>$(_BuildPath)/bin/$(_Path)</OutputPath>
    <IntermediateOutputPath>$(_BuildPath)/obj/$(_Path)</IntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(_BuildPath)/nuget/$(_PathId)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>