<Project>

  <Sdk Name="ViHo.PackAsAnalyzer" Version="1.0.1" />

  <PropertyGroup>

    <_SolutionRoot>$(MSBuildThisFileDirectory)</_SolutionRoot>
    <_RelativePath>$([MSBuild]::MakeRelative($(_SolutionRoot), $(MSBuildProjectDirectory)))</_RelativePath>

    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsProjectName>$(_RelativePath.Replace('\','.').Replace('/','.'))</ArtifactsProjectName>
    <ArtifactsPath>$([System.IO.Path]::GetTempPath())build</ArtifactsPath>

    <TargetFramework>net10.0</TargetFramework>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AnalysisMode>All</AnalysisMode>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

  </PropertyGroup>

</Project>
