<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Configuration>Release</Configuration>

    <DefineConstants>DebugLog</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="x/*" />
  </ItemGroup>
</Project>