<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

    <RootNamespace>Game</RootNamespace>
    <AssemblyName>Go</AssemblyName>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="core/**" />
    <Compile Remove="test/**" />
    <Compile Remove="x/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RLMatrix" Version="0.5.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="4.12.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="7.3.0.5690">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="core/x.csproj" />
  </ItemGroup>
</Project>