<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Configuration>Release</Configuration>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

    <RootNamespace>Core</RootNamespace>
    <AssemblyName>Core</AssemblyName>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>