
using System;
using static Axtae.Random.IRandom;

namespace Axtae.Random;

/// <summary>
/// Provides extension methods for <see cref="IRandom"/> implementations.
/// </summary>
/// <remarks>
/// These methods are available for both <see langword="struct"/> and
/// <see langword="class"/> implementations of <see cref="IRandom"/> via the
/// two <see langword="extension"/> blocks.
/// The overloads are provided to avoid boxing of struct instances.
/// </remarks>
#pragma warning disable RCS1263 // Invalid reference in a documentation comment
public static class IRandomExtensions {
  /// <summary>
  /// Provides extension methods for <see langword="struct"/> implementations
  /// </summary>
  /// <typeparam name="T">The random number generators type.</typeparam>
  /// <param name="rand">The random number generator.</param>
  extension<T>(ref T rand) where T : struct, IRandom, allows ref struct {
    /// <summary>
    /// Returns a random 64-bit unsigned integer in the range
    /// [0, <paramref name="max"/>).
    /// </summary>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than 0.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated. </returns>
    /// <remarks>
    /// <para>
    /// The method uses the unbiased rejection sampling technique to avoid
    /// modulo bias.
    /// It repeatedly generates random values until one falls below the
    /// rejection threshold,
    /// then returns the remainder modulo <paramref name="max"/>.
    /// </para>
    /// <para>
    /// If <paramref name="max"/> is 0, the method returns 0 without
    /// generating any random numbers.
    /// </para>
    /// </remarks>
    public ulong NextUInt64(ulong max) => T.NextUInt64(ref rand, max);

    /// <summary>
    /// Returns a random 64-bit unsigned integer in the range
    /// [<paramref name="min"/>, <paramref name="max"/>).
    /// </summary>
    /// <param name="min">The inclusive lower bound.</param>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than <paramref name="min"/>.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated.</returns>
    /// <remarks>
    /// If <paramref name="max"/> is less than <paramref name="min"/>,
    /// the method returns 0 without generating random  numbers.
    /// </remarks>
    public ulong NextUInt64(ulong min, ulong max)
      => T.NextUInt64(ref rand, min, max);

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1).
    /// </summary>
    /// <returns>A double in [0, 1).</returns>
    /// <remarks>
    /// The value is generated by shifting the 64-bit random value right by
    /// <see cref="DoubleShift"/> bits to obtain a 53-bit integer,
    /// then multiplying by <see cref="DoubleScale"/>.
    /// This yields a uniform distribution with 53 bits of precision.
    /// </remarks>
    public double NextDouble() => T.NextDouble(ref rand);

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1].
    /// </summary>
    /// <returns>A double in [0, 1], inclusive of 1.</returns>
    /// <remarks>
    /// The value is obtained by dividing the full 64-bit random integer by
    /// <see cref="ulong.MaxValue"/>. This gives a uniform distribution over
    /// all possible <see cref="double"/> values in that range, though the
    /// granularity is limited by the representation of <see cref="double"/>.
    /// </remarks>
    public double NextDoubleInclusive() => T.NextDoubleInclusive(ref rand);

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random
    /// <see cref="ulong"/> values.
    /// </summary>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    public void Fill(scoped Span<ulong> buffer) => T.Fill(ref rand, buffer);

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random values of
    /// any <see langword="unmanaged"/> type.
    /// </summary>
    /// <typeparam name="U">The unmanaged element type.</typeparam>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    /// <remarks>
    /// The method converts the span to a byte sequence,
    /// fills complete 8-byte chunks as <see cref="ulong"/> values,
    /// then copies any remaining bytes from an extra random value
    /// using a <c>switch</c> with fallthrough <c>goto case</c> statements.
    /// </remarks>
    public void Fill<U>(scoped Span<U> buffer) where U : unmanaged
      => T.Fill(ref rand, buffer);
  }

  /// <summary>
  /// Provides extension methods for <see langword="class"/> implementations
  /// </summary>
  /// <typeparam name="T">The random number generators type.</typeparam>
  /// <param name="rand">The random number generator.</param>
  extension<T>(T rand) where T : class, IRandom {
    /// <summary>
    /// Returns a random 64-bit unsigned integer in the range
    /// [0, <paramref name="max"/>).
    /// </summary>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than 0.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated. </returns>
    /// <remarks>
    /// <para>
    /// The method uses the unbiased rejection sampling technique to avoid
    /// modulo bias.
    /// It repeatedly generates random values until one falls below the
    /// rejection threshold,
    /// then returns the remainder modulo <paramref name="max"/>.
    /// </para>
    /// <para>
    /// If <paramref name="max"/> is 0, the method returns 0 without
    /// generating any random numbers.
    /// </para>
    /// </remarks>
    public ulong NextUInt64(ulong max) => T.NextUInt64(rand, max);

    /// <summary>
    /// Returns a random 64-bit unsigned integer in the range
    /// [<paramref name="min"/>, <paramref name="max"/>).
    /// </summary>
    /// <param name="min">The inclusive lower bound.</param>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than <paramref name="min"/>.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated.</returns>
    /// <remarks>
    /// If <paramref name="max"/> is less than <paramref name="min"/>,
    /// the method returns 0 without generating random  numbers.
    /// </remarks>
    public ulong NextUInt64(ulong min, ulong max)
      => T.NextUInt64(rand, min, max);

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1).
    /// </summary>
    /// <returns>A double in [0, 1).</returns>
    /// <remarks>
    /// The value is generated by shifting the 64-bit random value right by
    /// <see cref="DoubleShift"/> bits to obtain a 53-bit integer,
    /// then multiplying by <see cref="DoubleScale"/>.
    /// This yields a uniform distribution with 53 bits of precision.
    /// </remarks>
    public double NextDouble() => T.NextDouble(rand);

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1].
    /// </summary>
    /// <returns>A double in [0, 1], inclusive of 1.</returns>
    /// <remarks>
    /// The value is obtained by dividing the full 64-bit random integer by
    /// <see cref="ulong.MaxValue"/>. This gives a uniform distribution over
    /// all possible <see cref="double"/> values in that range, though the
    /// granularity is limited by the representation of <see cref="double"/>.
    /// </remarks>
    public double NextDoubleInclusive() => T.NextDoubleInclusive(rand);

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random
    /// <see cref="ulong"/> values.
    /// </summary>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    public void Fill(scoped Span<ulong> buffer) => T.Fill(rand, buffer);

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random values of
    /// any <see langword="unmanaged"/> type.
    /// </summary>
    /// <typeparam name="U">The unmanaged element type.</typeparam>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    /// <remarks>
    /// The method converts the span to a byte sequence,
    /// fills complete 8-byte chunks as <see cref="ulong"/> values,
    /// then copies any remaining bytes from an extra random value
    /// using a <c>switch</c> with fallthrough <c>goto case</c> statements.
    /// </remarks>
    public void Fill<U>(scoped Span<U> buffer) where U : unmanaged
      => T.Fill(rand, buffer);
  }
}
#pragma warning restore RCS1263 // Invalid reference in a documentation comment
