
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using static Axtae.Random.IRandom;

namespace Axtae.Random;

/// <summary>
/// Provides extension methods for <see cref="IRandom"/> implementations.
/// </summary>
/// <remarks>
/// These methods are available for both <see langword="struct"/> and
/// <see langword="class"/> implementations of <see cref="IRandom"/> via the
/// two <see langword="extension"/> blocks.
/// The overloads are provided to avoid boxing of struct instances.
/// </remarks>
public static class IRandomExtensions {
  extension<T>(ref T rand) where T : struct, IRandom, allows ref struct {
    /// <summary>
    /// Returns a random 64‑bit unsigned integer in the range
    /// [0, <paramref name="max"/>).
    /// </summary>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than 0.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated. </returns>
    /// <remarks>
    /// <para>
    /// The method uses the unbiased rejection sampling technique to avoid
    /// modulo bias.
    /// It repeatedly generates random values until one falls below the
    /// rejection threshold,
    /// then returns the remainder modulo <paramref name="max"/>.
    /// </para>
    /// <para>
    /// If <paramref name="max"/> is 0, the method returns 0 without
    /// generating any random numbers.
    /// </para>
    /// </remarks>
    public ulong NextUInt64(ulong max) {
      if (max is 0) return 0;
      ulong threshold = unchecked((0ul - max) % max);
      while (true) {
        ulong r = rand.NextUInt64();
        if (r >= threshold) return r % max;
      }
    }

    /// <summary>
    /// Returns a random 64‑bit unsigned integer in the range
    /// [<paramref name="min"/>, <paramref name="max"/>).
    /// </summary>
    /// <param name="min">The inclusive lower bound.</param>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than <paramref name="min"/>.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated.</returns>
    /// <remarks>
    /// If <paramref name="max"/> is less than <paramref name="min"/>,
    /// the method returns 0 without generating random  numbers.
    /// </remarks>
    public ulong NextUInt64(ulong min, ulong max) {
      if (min >= max) return 0;
      var range = max - min;
      return min + rand.NextUInt64(range);
    }

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1).
    /// </summary>
    /// <returns>A double in [0, 1).</returns>
    /// <remarks>
    /// The value is generated by shifting the 64‑bit random value right by
    /// <see cref="DoubleShift"/> bits to obtain a 53‑bit integer,
    /// then multiplying by <see cref="DoubleScale"/>.
    /// This yields a uniform distribution with 53 bits of precision.
    /// </remarks>
    public double NextDouble()
      => (rand.NextUInt64() >> DoubleShift) * DoubleScale;

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1].
    /// </summary>
    /// <returns>A double in [0, 1], inclusive of 1.</returns>
    /// <remarks>
    /// The value is obtained by dividing the full 64‑bit random integer by
    /// <see cref="ulong.MaxValue"/>. This gives a uniform distribution over
    /// all possible <see cref="double"/> values in that range, though the
    /// granularity is limited by the representation of <see cref="double"/>.
    /// </remarks>
    public double NextDoubleInclusive()
      => rand.NextUInt64() / (double)ulong.MaxValue;

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random
    /// <see cref="ulong"/> values.
    /// </summary>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    public void Fill(scoped Span<ulong> buffer) {
      if (buffer.IsEmpty) return;
      foreach (ref var value in buffer)
        value = rand.NextUInt64();
    }

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random values of
    /// any <see langword="unmanaged"/> type.
    /// </summary>
    /// <typeparam name="U">The unmanaged element type.</typeparam>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    /// <remarks>
    /// The method converts the span to a byte sequence,
    /// fills complete 8-byte chunks as <see cref="ulong"/> values,
    /// then copies any remaining bytes from an extra random value
    /// using a <c>switch</c> with fallthrough <c>goto case</c> statements.
    /// </remarks>
    public void Fill<U>(scoped Span<U> buffer) where U : unmanaged {
      if (buffer.IsEmpty) return;

      var bytes = MemoryMarshal.AsBytes(buffer);
      var sp = MemoryMarshal.Cast<byte, ulong>(bytes);
      rand.Fill(sp);

      int remaining = bytes.Length % 8;
      if (remaining is 0) return;

      ulong last = rand.NextUInt64();
      ref byte src = ref Unsafe.As<ulong, byte>(ref last);
      ref byte dst = ref bytes[^remaining];

#pragma warning disable S907 // "goto" statement should not be used
      switch (remaining) {
        case 7: Unsafe.Add(ref dst, 6) = Unsafe.Add(ref src, 6); goto case 6;
        case 6: Unsafe.Add(ref dst, 5) = Unsafe.Add(ref src, 5); goto case 5;
        case 5: Unsafe.Add(ref dst, 4) = Unsafe.Add(ref src, 4); goto case 4;
        case 4: Unsafe.Add(ref dst, 3) = Unsafe.Add(ref src, 3); goto case 3;
        case 3: Unsafe.Add(ref dst, 2) = Unsafe.Add(ref src, 2); goto case 2;
        case 2: Unsafe.Add(ref dst, 1) = Unsafe.Add(ref src, 1); goto case 1;
        case 1: dst = src; break;
      }
#pragma warning restore S907 // "goto" statement should not be used
    }
  }

  extension<T>(T rand) where T : class, IRandom {
    /// <summary>
    /// Returns a random 64‑bit unsigned integer in the range
    /// [0, <paramref name="max"/>).
    /// </summary>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than 0.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated. </returns>
    /// <remarks>
    /// <para>
    /// The method uses the unbiased rejection sampling technique to avoid
    /// modulo bias.
    /// It repeatedly generates random values until one falls below the
    /// rejection threshold,
    /// then returns the remainder modulo <paramref name="max"/>.
    /// </para>
    /// <para>
    /// If <paramref name="max"/> is 0, the method returns 0 without
    /// generating any random numbers.
    /// </para>
    /// </remarks>
    public ulong NextUInt64(ulong max) {
      if (max is 0) return 0;
      ulong threshold = unchecked((0ul - max) % max);
      while (true) {
        ulong r = rand.NextUInt64();
        if (r >= threshold) return r % max;
      }
    }

    /// <summary>
    /// Returns a random 64‑bit unsigned integer in the range
    /// [<paramref name="min"/>, <paramref name="max"/>).
    /// </summary>
    /// <param name="min">The inclusive lower bound.</param>
    /// <param name="max">
    /// The exclusive upper bound. Must be greater than <paramref name="min"/>.
    /// </param>
    /// <returns> A random <see cref="ulong"/> by Generated.</returns>
    /// <remarks>
    /// If <paramref name="max"/> is less than <paramref name="min"/>,
    /// the method returns 0 without generating random  numbers.
    /// </remarks>
    public ulong NextUInt64(ulong min, ulong max) {
      if (min >= max) return 0;
      var range = max - min;
      return min + rand.NextUInt64(range);
    }

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1).
    /// </summary>
    /// <returns>A double in [0, 1).</returns>
    /// <remarks>
    /// The value is generated by shifting the 64‑bit random value right by
    /// <see cref="DoubleShift"/> bits to obtain a 53‑bit integer,
    /// then multiplying by <see cref="DoubleScale"/>.
    /// This yields a uniform distribution with 53 bits of precision.
    /// </remarks>
    public double NextDouble()
      => (rand.NextUInt64() >> DoubleShift) * DoubleScale;

    /// <summary>
    /// Returns a random <see cref="double"/> in the range [0, 1].
    /// </summary>
    /// <returns>A double in [0, 1], inclusive of 1.</returns>
    /// <remarks>
    /// The value is obtained by dividing the full 64‑bit random integer by
    /// <see cref="ulong.MaxValue"/>. This gives a uniform distribution over
    /// all possible <see cref="double"/> values in that range, though the
    /// granularity is limited by the representation of <see cref="double"/>.
    /// </remarks>
    public double NextDoubleInclusive()
      => rand.NextUInt64() / (double)ulong.MaxValue;

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random
    /// <see cref="ulong"/> values.
    /// </summary>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    public void Fill(scoped Span<ulong> buffer) {
      if (buffer.IsEmpty) return;
      foreach (ref var value in buffer)
        value = rand.NextUInt64();
    }

    /// <summary>
    /// Fills the elements of a <see cref="Span{T}"/> with random values of
    /// any <see langword="unmanaged"/> type.
    /// </summary>
    /// <typeparam name="U">The unmanaged element type.</typeparam>
    /// <param name="buffer">
    /// The span to fill. If empty, the method returns immediately.
    /// </param>
    /// <remarks>
    /// The method converts the span to a byte sequence,
    /// fills complete 8-byte chunks as <see cref="ulong"/> values,
    /// then copies any remaining bytes from an extra random value
    /// using a <c>switch</c> with fallthrough <c>goto case</c> statements.
    /// </remarks>
    public void Fill<U>(scoped Span<U> buffer) where U : unmanaged {
      if (buffer.IsEmpty) return;

      var bytes = MemoryMarshal.AsBytes(buffer);
      var sp = MemoryMarshal.Cast<byte, ulong>(bytes);
      rand.Fill(sp);

      int remaining = bytes.Length % 8;
      if (remaining is 0) return;

      ulong last = rand.NextUInt64();
      ref byte src = ref Unsafe.As<ulong, byte>(ref last);
      ref byte dst = ref bytes[^remaining];

#pragma warning disable S907 // "goto" statement should not be used
      switch (remaining) {
        case 7: Unsafe.Add(ref dst, 6) = Unsafe.Add(ref src, 6); goto case 6;
        case 6: Unsafe.Add(ref dst, 5) = Unsafe.Add(ref src, 5); goto case 5;
        case 5: Unsafe.Add(ref dst, 4) = Unsafe.Add(ref src, 4); goto case 4;
        case 4: Unsafe.Add(ref dst, 3) = Unsafe.Add(ref src, 3); goto case 3;
        case 3: Unsafe.Add(ref dst, 2) = Unsafe.Add(ref src, 2); goto case 2;
        case 2: Unsafe.Add(ref dst, 1) = Unsafe.Add(ref src, 1); goto case 1;
        case 1: dst = src; break;
      }
#pragma warning restore S907 // "goto" statement should not be used
    }
  }
}

